package com.practice.core.controller;

import com.practice.common.ApiResponse;import com.practice.common.CrudSupport;import com.practice.common.BaseEntity;import com.practice.core.entity.*;import com.practice.core.repository.*;import com.practice.core.service.*;import jakarta.servlet.http.HttpServletRequest;import org.springframework.beans.factory.annotation.Value;import org.springframework.data.jpa.repository.JpaRepository;import org.springframework.web.bind.annotation.*;import java.util.*;

@RestController @RequestMapping("/api/auth") class AuthController { @Value("${app.token:panda-iot-demo-token}") String token; final PlatformCoreService service; AuthController(PlatformCoreService service){this.service=service;} @PostMapping("/login") ApiResponse<Map<String,Object>> login(@RequestBody Map<String,String> b, HttpServletRequest r){ return ApiResponse.ok(service.login(b.get("username"), b.get("password"), token, r.getRemoteAddr())); } }
@RestController @RequestMapping("/api/dashboard") class DashboardController { final PlatformCoreService s; DashboardController(PlatformCoreService s){this.s=s;} @GetMapping("/summary") ApiResponse<Map<String,Object>> summary(){return ApiResponse.ok(s.summary());} @GetMapping("/charts") ApiResponse<Map<String,Object>> charts(){return ApiResponse.ok(s.charts());} @GetMapping("/monitor") ApiResponse<Map<String,Object>> monitor(){return ApiResponse.ok(Map.of("cpu",42,"memory",63,"disk",58,"mqtt","running","http","running","jvmThreads",28));} }
@RestController @RequestMapping("/api/telemetry") class TelemetryController { final PlatformCoreService s; TelemetryController(PlatformCoreService s){this.s=s;} @PostMapping("/simulate") ApiResponse<Map<String,Object>> simulate(@RequestBody Map<String,Object> b){return ApiResponse.ok(s.simulate(b));} @GetMapping ApiResponse<List<TelemetryData>> list(){return ApiResponse.ok(s.recentTelemetry());} }
@RestController @RequestMapping("/api/alarms") class AlarmController extends CrudController<Alarm>{ final PlatformCoreService s; AlarmController(AlarmRepo r, CrudService<Alarm> c, PlatformCoreService s){super(r,c);this.s=s;} @PostMapping("/{id}/handle") ApiResponse<Alarm> handle(@PathVariable Long id,@RequestBody Map<String,Object>b){return ApiResponse.ok(s.handleAlarm(id,b));} @PostMapping("/{id}/close") ApiResponse<Alarm> close(@PathVariable Long id){return ApiResponse.ok(s.handleAlarm(id,Map.of("remark","关闭告警")));} }
@RestController @RequestMapping("/api/tasks") class TaskController extends CrudController<TaskJob>{ final PlatformCoreService s; TaskController(TaskJobRepo r, CrudService<TaskJob> c, PlatformCoreService s){super(r,c);this.s=s;} @PostMapping("/{id}/start") ApiResponse<TaskJob> start(@PathVariable Long id){return ApiResponse.ok(s.switchTask(id,true));} @PostMapping("/{id}/stop") ApiResponse<TaskJob> stop(@PathVariable Long id){return ApiResponse.ok(s.switchTask(id,false));} @GetMapping("/logs") ApiResponse<List<TaskLog>> logs(){return ApiResponse.ok(s.taskLogs());} }
@RestController @RequestMapping("/api/network-services") class NetworkServiceController extends CrudController<NetworkService>{ NetworkServiceController(NetworkServiceRepo r, CrudService<NetworkService> c){super(r,c);} @PostMapping("/{id}/start") ApiResponse<NetworkService> start(@PathVariable Long id){return status(id,"RUNNING");} @PostMapping("/{id}/stop") ApiResponse<NetworkService> stop(@PathVariable Long id){return status(id,"STOPPED");} }
@RestController @RequestMapping("/api/firmwares") class FirmwareController extends CrudController<Firmware>{ FirmwareController(FirmwareRepo r, CrudService<Firmware> c){super(r,c);} @PostMapping("/{id}/upgrade") ApiResponse<Firmware> upgrade(@PathVariable Long id,@RequestBody(required=false) Map<String,Object>b){ Firmware f=repo.findById(id).orElseThrow(); f.upgradeStatus= b==null?"UPGRADING":String.valueOf(b.getOrDefault("status","UPGRADING")); f.status=f.upgradeStatus; return ApiResponse.ok(repo.save(f)); } }
@RestController @RequestMapping("/api/ai-agents") class AiAgentController extends CrudController<AiAgent>{ final PlatformCoreService s; AiAgentController(AiAgentRepo r, CrudService<AiAgent> c, PlatformCoreService s){super(r,c);this.s=s;} @PostMapping("/chat") ApiResponse<Map<String,Object>> chat(@RequestBody Map<String,Object> b){return ApiResponse.ok(s.aiChat(b));} @PostMapping("/models") ApiResponse<Map<String,Object>> models(@RequestBody(required=false) Map<String,Object> b){return ApiResponse.ok(s.aiModels(b==null?Map.of():b));} }
@RestController @RequestMapping("/api/users") class UserController extends CrudController<SysUser>{ UserController(UserRepo r, CrudService<SysUser> c){super(r,c);} @Override @PostMapping ApiResponse<SysUser> create(@RequestBody SysUser body){ if (body.password == null || body.password.isBlank()) body.password="123456"; return ApiResponse.ok(repo.save(body)); } @Override @PutMapping("/{id}") ApiResponse<SysUser> update(@PathVariable Long id,@RequestBody SysUser body){ SysUser old=((UserRepo)repo).findById(id).orElseThrow(); if (body.password == null || body.password.isBlank()) body.password=null; return ApiResponse.ok(repo.save(CrudSupport.merge(old,body))); } }
@RestController @RequestMapping("/api/roles") class RoleController extends CrudController<Role>{ RoleController(RoleRepo r, CrudService<Role> c){super(r,c);} }
@RestController @RequestMapping("/api/product-categories") class ProductCategoryController extends CrudController<ProductCategory>{ ProductCategoryController(ProductCategoryRepo r, CrudService<ProductCategory> c){super(r,c);} }
@RestController @RequestMapping("/api/products") class ProductController extends CrudController<Product>{ ProductController(ProductRepo r, CrudService<Product> c){super(r,c);} }
@RestController @RequestMapping("/api/device-groups") class DeviceGroupController extends CrudController<DeviceGroup>{ DeviceGroupController(DeviceGroupRepo r, CrudService<DeviceGroup> c){super(r,c);} }
@RestController @RequestMapping("/api/devices") class DeviceController extends CrudController<Device>{ DeviceController(DeviceRepo r, CrudService<Device> c){super(r,c);} }
@RestController @RequestMapping("/api/rules") class RuleController extends CrudController<Rule>{ RuleController(RuleRepo r, CrudService<Rule> c){super(r,c);} }
@RestController @RequestMapping("/api/rule-audits") class RuleAuditController extends CrudController<RuleAudit>{ RuleAuditController(RuleAuditRepo r, CrudService<RuleAudit> c){super(r,c);} }
@RestController @RequestMapping("/api/scripts") class ScriptController extends CrudController<ParseScript>{ ScriptController(ParseScriptRepo r, CrudService<ParseScript> c){super(r,c);} }
@RestController @RequestMapping("/api/operation-logs") class OperationLogController extends CrudController<OperationLog>{ OperationLogController(OperationLogRepo r, CrudService<OperationLog> c){super(r,c);} }
@RestController @RequestMapping("/api/login-logs") class LoginLogController extends CrudController<LoginLog>{ LoginLogController(LoginLogRepo r, CrudService<LoginLog> c){super(r,c);} }
abstract class CrudController<T extends BaseEntity> { final JpaRepository<T,Long> repo; final CrudService<T> service; CrudController(JpaRepository<T,Long> repo, CrudService<T> service){this.repo=repo;this.service=service;} @GetMapping ApiResponse<List<T>> list(@RequestParam(required=false) String keyword){ return ApiResponse.ok(service.list(repo, keyword)); } @GetMapping("/{id}") ApiResponse<T> get(@PathVariable Long id){ return ApiResponse.ok(service.get(repo,id)); } @PostMapping ApiResponse<T> create(@RequestBody T body){ return ApiResponse.ok(service.create(repo,body)); } @PutMapping("/{id}") ApiResponse<T> update(@PathVariable Long id,@RequestBody T body){ return ApiResponse.ok(service.update(repo,id,body)); } @DeleteMapping("/{id}") ApiResponse<Boolean> delete(@PathVariable Long id){ return ApiResponse.ok(service.delete(repo,id)); } @PostMapping("/{id}/toggle") ApiResponse<T> toggle(@PathVariable Long id){ return ApiResponse.ok(service.toggle(repo,id)); } ApiResponse<T> status(Long id,String status){ return ApiResponse.ok(service.status(repo,id,status)); } }
