USE industrial_iot_platform;
INSERT INTO role(name, code, status, permissions, created_at, updated_at) VALUES ('超级管理员','admin','ENABLED','*:*:*',NOW(),NOW());
INSERT INTO sys_user(name, username, password, real_name, role_name, status, created_at, updated_at) VALUES ('平台管理员','admin','123456','PandaX管理员','超级管理员','ENABLED',NOW(),NOW());
INSERT INTO product_category(name, code, status, created_at, updated_at) VALUES ('工业传感器','sensor','ENABLED',NOW(),NOW()),('边缘网关','gateway','ENABLED',NOW(),NOW());
INSERT INTO product(name, code, status, category_id, protocol, manufacturer, created_at, updated_at) VALUES ('PandaX温湿度采集器','PDX-TH-100','ENABLED',1,'MQTT','PandaX实验室',NOW(),NOW()),('PandaX边缘网关','PDX-GW-200','ENABLED',2,'MQTT/HTTP','PandaX实验室',NOW(),NOW());
INSERT INTO device_group(name, code, status, created_at, updated_at) VALUES ('一号车间','workshop-1','ENABLED',NOW(),NOW()),('能源站','energy-station','ENABLED',NOW(),NOW());
INSERT INTO device(name, code, status, product_id, group_id, device_key, location, latitude, longitude, last_online_at, created_at, updated_at) VALUES ('注塑机温度传感器01','DEV-TH-001','ONLINE',1,1,'key-th-001','一号车间A区',31.2304,121.4737,NOW(),NOW(),NOW()),('空压站边缘网关01','DEV-GW-001','OFFLINE',2,2,'key-gw-001','能源站',NULL,NULL,NULL,NOW(),NOW());
INSERT INTO rule(name, code, status, metric, operator, threshold, enabled, alarm_level, created_at, updated_at) VALUES ('温度超过80℃自动告警','RULE-TEMP-80','ENABLED','temperature','>',80,TRUE,'HIGH',NOW(),NOW());
INSERT INTO network_service(name, code, status, type, host, port, up_messages, down_messages, created_at, updated_at) VALUES ('MQTT接入服务','mqtt-server','RUNNING','MQTT','0.0.0.0',1883,1280,640,NOW(),NOW());
INSERT INTO parse_script(name, code, status, language, script, created_at, updated_at) VALUES ('温湿度JSON解析脚本','parse-json-th','ENABLED','JavaScript','return {temperature: payload.temp, humidity: payload.hum};',NOW(),NOW());
INSERT INTO dashboard_screen(name, code, status, group_name, published, config_json, created_at, updated_at) VALUES ('PandaX工厂运行总览','screen-factory','PUBLISHED','生产看板',TRUE,'{"theme":"dark"}',NOW(),NOW());
INSERT INTO task_job(name, code, status, cron, running, created_at, updated_at) VALUES ('设备在线状态巡检','TASK-ONLINE-CHECK','RUNNING','0 */5 * * * ?',TRUE,NOW(),NOW());
INSERT INTO firmware(name, code, status, version, target_product, upgrade_status, file_url, created_at, updated_at) VALUES ('PandaX网关固件','FW-GW-1.0.0','ENABLED','v1.0.0','PandaX边缘网关','READY','/files/fw-gw-1.0.0.bin',NOW(),NOW());
INSERT INTO telemetry_data(device_id, device_name, temperature, humidity, pressure, payload, report_time) VALUES (1,'注塑机温度传感器01',88.6,61.0,101.2,'{"temperature":88.6,"humidity":61.0,"pressure":101.2}',NOW());
INSERT INTO alarm(name, code, status, device_id, device_name, level, type, content, created_at, updated_at) VALUES ('温度阈值告警-注塑机温度传感器01','ALM-DEMO-001','OPEN',1,'注塑机温度传感器01','HIGH','THRESHOLD','temperature=88.6 > 80.0，触发规则：温度超过80℃自动告警',NOW(),NOW());
INSERT INTO rule_audit(name, code, status, rule_id, device_id, result, detail, created_at, updated_at) VALUES ('规则审计-温度超过80℃自动告警','AUDIT-DEMO-001','HIT',1,1,'HIT','temperature=88.6 > 80.0',NOW(),NOW());
INSERT INTO task_log(name, code, status, task_id, result, detail, execute_time, created_at, updated_at) VALUES ('任务日志-设备在线状态巡检','TASK-LOG-001','SUCCESS',1,'巡检完成','模拟执行策略：0 */5 * * * ?',NOW(),NOW(),NOW());
INSERT INTO operation_log(name, code, status, module_name, action, operator, detail, created_at, updated_at) VALUES ('数据中心-模拟上报','OP-DEMO-001','SUCCESS','数据中心','模拟上报','admin','设备注塑机温度传感器01上报遥测数据并触发告警',NOW(),NOW());
INSERT INTO login_log(name, code, status, username, ip, success, created_at, updated_at) VALUES ('登录-admin','LOGIN-DEMO-001','SUCCESS','admin','127.0.0.1',TRUE,NOW(),NOW());
