-- MySQL 8.x schema for course delivery. The default runtime uses H2 + JPA auto DDL.
CREATE DATABASE IF NOT EXISTS industrial_iot_platform DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE industrial_iot_platform;

CREATE TABLE IF NOT EXISTS role (id BIGINT PRIMARY KEY AUTO_INCREMENT, name VARCHAR(100), code VARCHAR(100), status VARCHAR(30), remark VARCHAR(255), permissions VARCHAR(1000), created_at DATETIME, updated_at DATETIME);
CREATE TABLE IF NOT EXISTS sys_user (id BIGINT PRIMARY KEY AUTO_INCREMENT, name VARCHAR(100), code VARCHAR(100), status VARCHAR(30), remark VARCHAR(255), username VARCHAR(100), password VARCHAR(100), real_name VARCHAR(100), role_name VARCHAR(100), created_at DATETIME, updated_at DATETIME);
CREATE TABLE IF NOT EXISTS product_category (id BIGINT PRIMARY KEY AUTO_INCREMENT, name VARCHAR(100), code VARCHAR(100), status VARCHAR(30), remark VARCHAR(255), parent_id BIGINT, created_at DATETIME, updated_at DATETIME);
CREATE TABLE IF NOT EXISTS product (id BIGINT PRIMARY KEY AUTO_INCREMENT, name VARCHAR(100), code VARCHAR(100), status VARCHAR(30), remark VARCHAR(255), category_id BIGINT, protocol VARCHAR(50), manufacturer VARCHAR(100), created_at DATETIME, updated_at DATETIME);
CREATE TABLE IF NOT EXISTS device_group (id BIGINT PRIMARY KEY AUTO_INCREMENT, name VARCHAR(100), code VARCHAR(100), status VARCHAR(30), remark VARCHAR(255), parent_id BIGINT, created_at DATETIME, updated_at DATETIME);
CREATE TABLE IF NOT EXISTS device (id BIGINT PRIMARY KEY AUTO_INCREMENT, name VARCHAR(100), code VARCHAR(100), status VARCHAR(30), remark VARCHAR(255), product_id BIGINT, group_id BIGINT, device_key VARCHAR(100), location VARCHAR(255), latitude DOUBLE, longitude DOUBLE, last_online_at DATETIME, created_at DATETIME, updated_at DATETIME);
CREATE TABLE IF NOT EXISTS telemetry_data (id BIGINT PRIMARY KEY AUTO_INCREMENT, device_id BIGINT, device_name VARCHAR(100), temperature DOUBLE, humidity DOUBLE, pressure DOUBLE, payload TEXT, report_time DATETIME);
CREATE TABLE IF NOT EXISTS alarm (id BIGINT PRIMARY KEY AUTO_INCREMENT, name VARCHAR(100), code VARCHAR(100), status VARCHAR(30), remark VARCHAR(255), device_id BIGINT, device_name VARCHAR(100), level VARCHAR(30), type VARCHAR(50), content VARCHAR(1000), handler VARCHAR(100), handled_at DATETIME, created_at DATETIME, updated_at DATETIME);
CREATE TABLE IF NOT EXISTS rule (id BIGINT PRIMARY KEY AUTO_INCREMENT, name VARCHAR(100), code VARCHAR(100), status VARCHAR(30), remark VARCHAR(255), metric VARCHAR(50), operator VARCHAR(10), threshold DOUBLE, enabled BOOLEAN, alarm_level VARCHAR(30), created_at DATETIME, updated_at DATETIME);
CREATE TABLE IF NOT EXISTS rule_audit (id BIGINT PRIMARY KEY AUTO_INCREMENT, name VARCHAR(100), code VARCHAR(100), status VARCHAR(30), remark VARCHAR(255), rule_id BIGINT, device_id BIGINT, result VARCHAR(30), detail VARCHAR(1000), created_at DATETIME, updated_at DATETIME);
CREATE TABLE IF NOT EXISTS network_service (id BIGINT PRIMARY KEY AUTO_INCREMENT, name VARCHAR(100), code VARCHAR(100), status VARCHAR(30), remark VARCHAR(255), type VARCHAR(50), host VARCHAR(100), port INT, up_messages BIGINT, down_messages BIGINT, created_at DATETIME, updated_at DATETIME);
CREATE TABLE IF NOT EXISTS parse_script (id BIGINT PRIMARY KEY AUTO_INCREMENT, name VARCHAR(100), code VARCHAR(100), status VARCHAR(30), remark VARCHAR(255), script TEXT, language VARCHAR(50), created_at DATETIME, updated_at DATETIME);
CREATE TABLE IF NOT EXISTS dashboard_screen (id BIGINT PRIMARY KEY AUTO_INCREMENT, name VARCHAR(100), code VARCHAR(100), status VARCHAR(30), remark VARCHAR(255), group_name VARCHAR(100), published BOOLEAN, config_json TEXT, created_at DATETIME, updated_at DATETIME);
CREATE TABLE IF NOT EXISTS video_device (id BIGINT PRIMARY KEY AUTO_INCREMENT, name VARCHAR(100), code VARCHAR(100), status VARCHAR(30), remark VARCHAR(255), channel_no VARCHAR(100), stream_url VARCHAR(500), location VARCHAR(255), created_at DATETIME, updated_at DATETIME);
CREATE TABLE IF NOT EXISTS video_stream_proxy (id BIGINT PRIMARY KEY AUTO_INCREMENT, name VARCHAR(100), code VARCHAR(100), status VARCHAR(30), remark VARCHAR(255), video_device_id BIGINT, play_url VARCHAR(500), protocol VARCHAR(50), created_at DATETIME, updated_at DATETIME);
CREATE TABLE IF NOT EXISTS video_alarm_task (id BIGINT PRIMARY KEY AUTO_INCREMENT, name VARCHAR(100), code VARCHAR(100), status VARCHAR(30), remark VARCHAR(255), video_device_id BIGINT, algorithm VARCHAR(100), enabled BOOLEAN, created_at DATETIME, updated_at DATETIME);
CREATE TABLE IF NOT EXISTS task_job (id BIGINT PRIMARY KEY AUTO_INCREMENT, name VARCHAR(100), code VARCHAR(100), status VARCHAR(30), remark VARCHAR(255), cron VARCHAR(100), running BOOLEAN, last_result VARCHAR(500), created_at DATETIME, updated_at DATETIME);
CREATE TABLE IF NOT EXISTS task_log (id BIGINT PRIMARY KEY AUTO_INCREMENT, name VARCHAR(100), code VARCHAR(100), status VARCHAR(30), remark VARCHAR(255), task_id BIGINT, result VARCHAR(100), detail VARCHAR(1000), execute_time DATETIME, created_at DATETIME, updated_at DATETIME);
CREATE TABLE IF NOT EXISTS firmware (id BIGINT PRIMARY KEY AUTO_INCREMENT, name VARCHAR(100), code VARCHAR(100), status VARCHAR(30), remark VARCHAR(255), version VARCHAR(100), target_product VARCHAR(100), upgrade_status VARCHAR(50), file_url VARCHAR(500), created_at DATETIME, updated_at DATETIME);
CREATE TABLE IF NOT EXISTS operation_log (id BIGINT PRIMARY KEY AUTO_INCREMENT, name VARCHAR(100), code VARCHAR(100), status VARCHAR(30), remark VARCHAR(255), module_name VARCHAR(100), action VARCHAR(100), operator VARCHAR(100), detail VARCHAR(1000), created_at DATETIME, updated_at DATETIME);
CREATE TABLE IF NOT EXISTS login_log (id BIGINT PRIMARY KEY AUTO_INCREMENT, name VARCHAR(100), code VARCHAR(100), status VARCHAR(30), remark VARCHAR(255), username VARCHAR(100), ip VARCHAR(100), success BOOLEAN, created_at DATETIME, updated_at DATETIME);
